import { expect, test } from '@playwright/test';
import { openFirstRunFixture } from './fixtures/first-run-page';

test.use({ locale: 'de-DE' });
test('non-Russian system language defaults to English and overrides survive reload', async ({ page }) => {
  await openFirstRunFixture(page);
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  await page.getByTestId('start-button').click();
  await page.getByTestId('check-continue-button').click();
  for (let step = 1; step <= 5; step++) {
    await expect(page.getByTestId('step-counter')).toHaveText(`Step ${step} of 6`);
    if (step === 3) await page.getByTestId('choose-folder-button').click();
    await page.getByTestId('onboarding-next-button').click();
  }
  await page.getByTestId('run-test-button').click();
  await page.getByTestId('complete-onboarding-button').click();
  const language = page.getByRole('combobox', { name: 'Interface language' });
  await expect(language).toHaveText('Use Windows language');
  const languageBounds = await language.boundingBox();
  const settingsBounds = await page.getByRole('button', { name: 'Settings', exact: true }).boundingBox();
  expect(languageBounds!.y + languageBounds!.height).toBeLessThanOrEqual(settingsBounds!.y);
  await expect(page.getByRole('radio', { name: 'Application', exact: true })).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Interface language' }).click();
  await page.getByRole('option', { name: 'Русский', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('lang', 'ru');
  await expect(page.getByRole('combobox', { name: 'Язык интерфейса' })).toHaveText('Русский');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('lang', 'ru');
  await expect(page.getByRole('combobox', { name: 'Язык интерфейса' })).toHaveText('Русский');
  await page.getByRole('button', { name: 'Свернуть боковое меню', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Язык интерфейса' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Язык интерфейса' }).focus();
  await expect(page.getByRole('combobox', { name: 'Язык интерфейса' })).toBeFocused();
  const collapsedBounds = await page.getByRole('combobox', { name: 'Язык интерфейса' }).boundingBox();
  expect(collapsedBounds!.width).toBeLessThan(languageBounds!.width);
  await page.getByRole('combobox', { name: 'Язык интерфейса' }).click();
  await page.getByRole('option', { name: 'English', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Interface language' })).toHaveText('English');
  await page.reload();
  await expect(page.getByRole('combobox', { name: 'Interface language' })).toHaveText('English');
  await expect(page.getByRole('button', { name: 'Expand sidebar', exact: true })).toHaveAttribute('aria-expanded', 'false');
  await page.getByRole('combobox', { name: 'Interface language' }).click();
  await page.getByRole('option', { name: 'Use Windows language', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  await page.reload();
  await expect(page.getByRole('combobox', { name: 'Interface language' })).toHaveText('Use Windows language');
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('radio', { name: 'Application', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Interface language' })).toHaveCount(1);
});
