import {test,expect} from '@playwright/test';
if(process.env.PLAYWRIGHT_CHANNEL)test.use({channel:process.env.PLAYWRIGHT_CHANNEL});
test('constructs, drags and remembers a recording name preset',async({page})=>{
 await page.setViewportSize({width:1120,height:780});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/naming-qa',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><body style="background:#101011;padding:40px"><div id="root" style="max-width:720px;margin:auto"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module">import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {RecordingNameSettings} from '/src/naming/NamingSettings.tsx';import {defaults} from '/src/naming/model.ts';import '/src/styles/global.css';window.__TAURI_INTERNALS__={invoke:async(cmd,args)=>{if(cmd==='get_recording_names')return JSON.parse(localStorage.getItem('fixture-names')??'null')??defaults();if(cmd==='set_recording_names'){window.savedNames=args.settings;localStorage.setItem('fixture-names',JSON.stringify(args.settings));}}};ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(RecordingNameSettings));</script></body></html>`}));
 await page.goto('/naming-qa');const editor=page.getByRole('textbox',{name:'Конструктор имени записи'});await expect(page.getByLabel('Пример имени записи')).toContainText('Cyberpunk 2077 2023.03.27 - 13.30.59.62.DVR');
 await editor.click();await page.keyboard.press('Control+A');await page.keyboard.type('Мой  момент');
 const caret=await editor.evaluate(el=>{const r=document.createRange();r.setStart(el.firstChild!,4);r.collapse(true);const b=r.getBoundingClientRect(),p=el.getBoundingClientRect();return {x:b.x-p.x-2,y:b.y-p.y+b.height/2};});
 await page.getByRole('button',{name:'Название игры',exact:true}).dragTo(editor,{targetPosition:caret});
 await expect(page.getByLabel('Пример имени записи')).toHaveText('Мой Cyberpunk 2077 момент.mp4');
 await page.getByRole('button',{name:'Счётчик',exact:true}).click();await expect(editor.locator('[data-token=counter]')).toHaveCount(1);await editor.locator('[data-token=counter]').dragTo(editor,{targetPosition:{x:18,y:35}});await expect(editor.locator('[data-token]').first()).toHaveAttribute('data-token','counter');
 await page.getByLabel('Название нового пресета').fill('Мои моменты');await page.getByRole('button',{name:'Сохранить пресет',exact:true}).click();
 await expect(page.getByRole('combobox',{name:'Пресет имени записи'})).toHaveText('Мои моменты');expect(await page.evaluate(()=>(window as any).savedNames.presets.at(-1).parts.some((p:any)=>p.kind==='token'&&p.value==='game'))).toBe(true);
 await page.reload();await expect(page.getByRole('combobox',{name:'Пресет имени записи'})).toHaveText('Мои моменты');
 await page.screenshot({path:test.info().outputPath('recording-names.png')});await editor.click();await page.keyboard.press('End');await page.keyboard.type(' test');await page.getByRole('combobox',{name:'Пресет имени записи'}).click();await page.getByRole('option',{name:'NVIDIA ShadowPlay',exact:true}).click();await expect(page.getByRole('dialog',{name:'Переключить пресет?'})).toBeVisible();await page.getByRole('button',{name:'Продолжить редактирование'}).click();await expect(editor).toContainText('test');await page.getByRole('combobox',{name:'Пресет имени записи'}).click();await page.getByRole('option',{name:'NVIDIA ShadowPlay',exact:true}).click();await page.getByRole('button',{name:'Переключить без сохранения'}).click();await expect(page.getByLabel('Пример имени записи')).toContainText('.DVR.mp4');expect(errors).toEqual([]);
});
