import {expect,test} from '@playwright/test';
if(process.env.PLAYWRIGHT_CHANNEL)test.use({channel:process.env.PLAYWRIGHT_CHANNEL});
test('replay hero preserves its save action',async({page})=>{
 await page.setViewportSize({width:1120,height:780});
 await page.route('**/recording-qa',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><body style="background:#101011;padding:40px"><div id="root"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module">import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {RecordingControls} from '/src/components/RecordingControls.tsx';import {createDraftDefaults} from '/src/config/defaults.ts';import '/src/styles/global.css';const config={...createDraftDefaults(),onboarding_completed:true,monitor_id:'mon-0',width:1920,height:1080,fps:60,bitrate:12000000,system_audio:'disabled',microphone:'disabled',output_directory:'C:/Clips',replay_seconds:120};const snapshot={revision:1,lifecycle:'ready',replayActive:true,continuousRecordingActive:false,replaySeconds:120,metrics:{},lastError:null};ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(RecordingControls,{snapshot,activeConfig:config,onStartReplay:()=>{},onStopReplay:()=>{},onSaveReplay:()=>{window.saved=true;},onToggleContinuous:()=>{}}));</script></body></html>`}));
 const artwork=page.waitForResponse(r=>r.url().includes('replay-hero.png')&&r.ok());await page.goto('/recording-qa');await artwork;
 const card=page.getByRole('region',{name:'Мгновенный повтор'});await expect(card).toBeVisible();await card.screenshot({path:test.info().outputPath('replay-hero.png')});
 await page.getByTestId('save-replay-button').click();expect(await page.evaluate(()=>(window as any).saved)).toBe(true);
});
