import {ConfirmDialog} from '../components/Primitives';
import {NativeSelect,NativeSelectOption} from '../components/ui/native-select';
import {readAutosaves,writeAutosave,validRecoveryId,type Recovery} from './autosave';
import {registerNavigationGuard} from './navigationGuard';
import {useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {captureEditorWindow} from './editorWindow';
import {isWindowHidden,subscribeWindowVisibility} from '../app/windowVisibility';
import {getCurrentWindow} from '@tauri-apps/api/window';
import {TimelineMenu,type MenuAction} from './TimelineMenu';
import {PreviewTransform} from './PreviewTransform';
import {invoke,convertFileSrc} from '@tauri-apps/api/core';
import {Maximize,Minimize,ArrowUp,ArrowDown,ArrowLeft,Minus,X,Play,Pause,Scissors,Trash2,Undo2,Redo2,Plus,Save,FolderOpen,Download,Type,Package,Volume2,Film,Unlink} from 'lucide-react';
import {duplicate,snapDelta,reorderTrack,addAsset,changeGroup,changeSource,emptyProject,exportPlan,length,newItem,remove,split,type Asset,type Item,type Project} from './model';

import './editor.css';
import {TimelineLevel} from './TimelineLevel';
import {subscribeImportProgress,formatImportProgress,type ImportProgress} from './importProgress';
import {PlaybackClock,PlaybackTime,PlaybackActive} from './playbackClock';
import {EditorMedia as Media} from './EditorMedia';
type Status={state?:string;progress?:number;error?:string;path?:string;bytes?:number;attempt?:number};
function discordPreferences():{enabled:boolean;limit:number}{try{const p=JSON.parse(localStorage.getItem('rebcap.editor.discord')??'{}');return {enabled:p.enabled===true,limit:[20,50,500].includes(p.limit)?p.limit:20};}catch{return {enabled:false,limit:20};}}
const seconds=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toFixed(2).padStart(5,'0')}`;
function prepareAsset(a:Asset):Asset {return {...a,url:a.url?convertFileSrc(a.url):undefined,audioUrls:a.audioUrls?.map(t=>({...t,path:convertFileSrc(t.path)}))};}
function clean(p:Project):Project{return {...p,assets:p.assets.map(({url:_,audioUrls:__,missing:___,previewDirectory:____,...a})=>a)};}
export function ClipEditor({clipName,onClose}:{clipName?:string;onClose:()=>void}) {
 const [project,setProject]=useState<Project>(()=>({...emptyProject(),recoveryId:crypto.randomUUID()}));const current=useRef(project);current.current=project;
 const clock=useMemo(()=>new PlaybackClock(),[]);const setTime=clock.setTime;
 const time=clock.getSnapshot();
 const [selected,setSelected]=useState<string>();const [playing,setPlaying]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 // Playback ticks do not change project, so serialization runs only on edits.
 const projectContent=useMemo(()=>JSON.stringify(clean(project)),[project]);
 const [savedContent,setSavedContent]=useState<string|null>(()=>projectContent);
 const dirty=projectContent!==savedContent;
 const projectSession=useRef(0);
 const editorOwner=useRef(crypto.randomUUID());
 const mounted=useRef(true);
 const nativeSession=useRef<Promise<unknown>|null>(null);
 async function ensureNativeSession(){
  if(!mounted.current)throw 'editor.operation_cancelled';
  nativeSession.current??=invoke('editor_begin_session',{owner:editorOwner.current});
  const registration=nativeSession.current;
  try{await registration;}catch(e){if(nativeSession.current===registration)nativeSession.current=null;throw e;}
  if(!mounted.current)throw 'editor.operation_cancelled';
 }
 function discardPreviews(assets:Asset[]){const directories=assets.flatMap(a=>a.previewDirectory?[a.previewDirectory]:[]);if(directories.length)void invoke('editor_release_previews',{directories,owner:editorOwner.current}).catch(()=>{});}
 const importRequest=useRef(0);
 const importCancelFailed=useRef(false);
 const [importing,setImporting]=useState(false);
 const [importProgress,setImportProgress]=useState<ImportProgress>();
 const progressRelease=useRef<(()=>void)|undefined>(undefined);
 const [recoveries,setRecoveries]=useState<Recovery[]>([]);
 const [recoveryId,setRecoveryId]=useState('');
 const [recoveryWarning,setRecoveryWarning]=useState('');
 const [autosaveError,setAutosaveError]=useState('');
 const [autosaveStatus,setAutosaveStatus]=useState('Автокопия появится после изменений.');
 const autosaveActive=useRef(false);
 function persistAutosave(p:Project){try{writeAutosave(localStorage,{id:p.recoveryId!,savedAt:Date.now(),project:clean(p)});setAutosaveError('');setAutosaveStatus('Автокопия сохранена на этом компьютере.');return true;}catch(e){setAutosaveError(`Автокопия не сохранена: ${String(e)}. Сохраните проект в .rebcap или повторите автосохранение.`);return false;}}

 const onPlaybackError=useCallback((message:string)=>{setPlaying(false);setError(message);},[]);
 const [ripple,setRipple]=useState(true);const [zoom,setZoom]=useState(30);const [historyRevision,refreshHistory]=useState(0);const past=useRef<Project[]>([]),future=useRef<Project[]>([]);
 const [context,setContext]=useState<{x:number;y:number;id:string}>();
 const [inspectorVisible,setInspectorVisible]=useState(true);const [fullscreen,setFullscreen]=useState(false);const [snapAt,setSnapAt]=useState<number>();
 const [exporting,setExporting]=useState(false);const [status,setStatus]=useState<Status>({});const [bitrate,setBitrate]=useState(12);const [outWidth,setOutWidth]=useState(1920),[outHeight,setOutHeight]=useState(1080),[outFps,setOutFps]=useState(60);const [discord,setDiscord]=useState(()=>discordPreferences().enabled);const [discordLimitMb,setDiscordLimitMb]=useState(()=>discordPreferences().limit);const [priority,setPriority]=useState('auto');const [openPrompt,setOpenPrompt]=useState(false);const [closePrompt,setClosePrompt]=useState(false);const [restorePrompt,setRestorePrompt]=useState(false);
 useEffect(()=>{try{localStorage.setItem('rebcap.editor.discord',JSON.stringify({enabled:discord,limit:discordLimitMb}));}catch{/* Manual export remains available. */}},[discord,discordLimitMb]);
 const windowSession=useRef<ReturnType<typeof captureEditorWindow>|null>(null);
 useEffect(()=>{if(!('__TAURI_INTERNALS__' in window))return;const session=captureEditorWindow(getCurrentWindow());windowSession.current=session;return()=>{void session.restore().catch(()=>{});};},[]);
 const started=useRef(false);const total=useMemo(()=>length(project),[project.items]);
 const assetsById=useMemo(()=>new Map(project.assets.map(asset=>[asset.id,asset])),[project.assets]);
 const selection=useMemo(()=>project.items.find(i=>i.id===selected),[project.items,selected]);const selectedAsset=selection?.asset?assetsById.get(selection.asset):undefined;const isRendering=status.state==='running';
 const previewItems=useMemo(()=>[...project.items].sort((a,b)=>a.track-b.track),[project.items]);
 const trackItems=useMemo(()=>{const grouped=new Map<number,Item[]>();for(const item of project.items){const items=grouped.get(item.track);if(items)items.push(item);else grouped.set(item.track,[item]);}return grouped;},[project.items]);
 const tracks=useMemo(()=>[...trackItems.keys()].sort((a,b)=>b-a),[trackItems]);
 const previewWrap=useRef<HTMLDivElement>(null);const [previewSize,setPreviewSize]=useState({width:640,height:360});
 useEffect(()=>{const el=previewWrap.current;if(!el)return;const observer=new ResizeObserver(()=>{const availableWidth=Math.max(1,el.clientWidth-48),availableHeight=Math.max(1,el.clientHeight-48);const scale=Math.min(availableWidth/project.width,availableHeight/project.height);setPreviewSize({width:project.width*scale,height:project.height*scale});});observer.observe(el);return()=>observer.disconnect();},[project.width,project.height]);
 const change=useCallback((next:Project)=>{past.current=[...past.current.slice(-99),current.current];future.current=[];setProject(next);setError('');refreshHistory(v=>v+1);},[]);
 const undo=useCallback(()=>{const p=past.current.pop();if(p){future.current.push(current.current);setProject(p);refreshHistory(v=>v+1);}},[]);
 const redo=useCallback(()=>{const p=future.current.pop();if(p){past.current.push(current.current);setProject(p);refreshHistory(v=>v+1);}},[]);
 function replaceProject(next:Project,saved:boolean){if(autosaveActive.current)persistAutosave(current.current);autosaveActive.current=false;next={...next,recoveryId:validRecoveryId(next.recoveryId)?next.recoveryId:crypto.randomUUID()};projectSession.current++;past.current=[];future.current=[];drag.current=null;setContext(undefined);setSnapAt(undefined);current.current=next;setProject(next);setSavedContent(saved?JSON.stringify(clean(next)):null);refreshHistory(v=>v+1);setTime(0);setPlaying(false);setSelected(undefined);setOutWidth(next.width);setOutHeight(next.height);setOutFps(next.fps);}
 async function task<T>(action:(operationId?:string)=>Promise<T>,cancellable=false):Promise<T|undefined>{
  const request=importRequest.current;
  const operationId=cancellable?crypto.randomUUID():undefined;
  const active=()=>mounted.current&&request===importRequest.current;
  let releaseProgress:(()=>void)|undefined;
  setBusy(true);if(cancellable){setImporting(true);setImportProgress(undefined);}setError('');
  try{
   if(operationId){
    const unlisten=await subscribeImportProgress(editorOwner.current,operationId,progress=>{if(active())setImportProgress(progress);},active).catch(()=>()=>{});
    let released=false;
    releaseProgress=()=>{if(!released){released=true;unlisten();if(progressRelease.current===releaseProgress)progressRelease.current=undefined;}};
    if(active())progressRelease.current=releaseProgress;else releaseProgress();
   }
   if(cancellable&&!active())return undefined;
   return await action(operationId);
  }catch(e){if(String(e)==='editor.operation_cancelled')setNotice('Импорт отменён.');else if(!cancellable||request===importRequest.current)setError(String(e)==='editor.operation_timeout'?'Подготовка медиа превысила время ожидания. Попробуйте снова или выберите другой файл.':String(e)==='editor.output_limit'?'Не удалось подготовить медиа: превышен допустимый объём данных.':String(e));return undefined;}
  finally{releaseProgress?.();setBusy(false);if(cancellable){setImporting(false);setImportProgress(undefined);if(request!==importRequest.current&&!importCancelFailed.current)setNotice('Импорт отменён.');}}
 }
 function cancelImport(){importCancelFailed.current=false;importRequest.current++;progressRelease.current?.();setImportProgress(undefined);setNotice('Отменяем импорт…');void invoke('editor_cancel_import',{owner:editorOwner.current}).catch(e=>{importCancelFailed.current=true;setNotice('');setError(`Не удалось подтвердить отмену импорта: ${String(e)}`);});}
 async function importMedia(name?:string,replace?:string){const time=clock.getSnapshot();const request=importRequest.current;await task(async operationId=>{await ensureNativeSession();if(request!==importRequest.current)return;const raw=await invoke<Asset|null>('editor_import',{name:name??null,owner:editorOwner.current,operationId});if(!raw)return;if(!mounted.current||request!==importRequest.current){discardPreviews([raw]);return;}const a=prepareAsset(raw);if(replace){const old=current.current.assets.find(a=>a.id===replace);if(!old)return;const p={...current.current,assets:current.current.assets.map(v=>v.id===replace?{...a,id:replace}:v),items:current.current.items.map(i=>i.asset===replace?{...i,source:Math.min(i.source,Math.max(0,a.duration-.05)),duration:Math.min(i.duration,Math.max(.05,a.duration-i.source)),stream:i.kind==='audio'?(a.audio[old.audio.indexOf(i.stream)]??a.audio[0]??0):i.stream}:i)};change(p);}else{const p=addAsset(current.current,a,current.current.items.length?time:0);if(!current.current.items.length){p.name=a.name.replace(/\.[^.]+$/,'');if(a.kind==='video'&&a.width&&a.height){p.width=a.width;p.height=a.height;setOutWidth(a.width);setOutHeight(a.height);}}change(p);setSelected(p.items.at(-1)?.id);}},true);}
 useEffect(()=>{if(started.current)return;started.current=true;try{const result=readAutosaves(localStorage);setRecoveries(result.entries);setRecoveryId(result.entries[0]?.id??'');if(result.damaged)setRecoveryWarning(`Повреждённых автокопий: ${result.damaged}. Они оставлены в хранилище; остальные проекты доступны для восстановления.`);if(!clipName&&result.entries.length)setRestorePrompt(true);}catch(e){setAutosaveError(`Автокопия недоступна: ${String(e)}. Сохраните проект в .rebcap.`);}if(clipName)void importMedia(clipName);},[]);
 useEffect(()=>{if(!dirty&&!autosaveActive.current)return;autosaveActive.current=true;setAutosaveStatus('Автокопия ожидает сохранения.');const handle=setTimeout(()=>persistAutosave(project),800);return()=>clearTimeout(handle);},[project,dirty]);
 useEffect(()=>{if(!playing)return;let frame=0;let prev=performance.now();function tick(now:number){const delta=(now-prev)/1000;prev=now;setTime(t=>{if(t+delta>=total){setPlaying(false);return total;}return t+delta;});frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,total]);
 useEffect(()=>{const pauseWhenHidden=()=>{if(isWindowHidden())setPlaying(false);};pauseWhenHidden();return subscribeWindowVisibility(pauseWhenHidden);},[]);
 useEffect(()=>{
  if(!isRendering)return;
  let disposed=false;
  let timer:ReturnType<typeof setTimeout>;
  async function poll(){
   let running=true;
   try{
    const s=await invoke<Status>('editor_status');
    if(disposed)return;
    setStatus(s);
    running=s.state==='running';
    if(s.state==='done')setNotice(`Видео сохранено: ${s.path} · ${((s.bytes??0)/1e6).toFixed(2)} МБ`);
    if(s.state==='error')setError(s.error??'Ошибка экспорта');
   }catch(e){if(disposed)return;setError(String(e));}
   if(!disposed&&running)timer=setTimeout(()=>{void poll();},400);
  }
  timer=setTimeout(()=>{void poll();},400);
  return()=>{disposed=true;clearTimeout(timer);};
 },[isRendering]);
 const ownedPreviews=useRef(new Set<string>());
 useEffect(()=>{
  const retained=new Set([project,...past.current,...future.current].flatMap(p=>p.assets.flatMap(a=>a.previewDirectory?[a.previewDirectory]:[])));
  for(const directory of retained)ownedPreviews.current.add(directory);
  if(busy||isRendering)return;
  const retired=[...ownedPreviews.current].filter(directory=>!retained.has(directory));
  if(!retired.length)return;
  // Keep failed releases owned for retry on the next project/history change.
  void invoke('editor_release_previews',{directories:retired,owner:editorOwner.current}).then(()=>{
   for(const directory of retired)ownedPreviews.current.delete(directory);
  }).catch(e=>setError(`Не удалось освободить временные превью: ${String(e)}`));
 },[project,historyRevision,busy,isRendering]);
 const releaseTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{mounted.current=true;clearTimeout(releaseTimer.current);return()=>{mounted.current=false;releaseTimer.current=setTimeout(()=>{
  progressRelease.current?.();
  async function release(attempt=0){try{await (nativeSession.current??Promise.resolve()).catch(()=>{});await invoke('editor_release',{owner:editorOwner.current});}catch(e){if(attempt<3)setTimeout(()=>{void release(attempt+1);},250*(attempt+1));else console.error('Не удалось освободить временные превью редактора',e);}}
  void release();
 },0);};},[]);
 async function save(pack=false,template=false){const snapshot=clean(current.current),content=JSON.stringify(snapshot),session=projectSession.current;return (await task(async()=>{const path=await invoke<string|null>('editor_save',{project:{...snapshot,template},pack});if(!path||session!==projectSession.current)return false;setNotice(`${template?'Шаблон':'Проект'} сохранён: ${path}`);if(!template)setSavedContent(content);return template||JSON.stringify(clean(current.current))===content;}))??false;}
 async function openProject(confirmed=false){if(dirty&&!confirmed){setOpenPrompt(true);return;}setPlaying(false);const request=importRequest.current;await task(async operationId=>{await ensureNativeSession();if(request!==importRequest.current)return;const p=await invoke<Project|null>('editor_open',{owner:editorOwner.current,operationId});if(p&&(!mounted.current||request!==importRequest.current)){discardPreviews(p.assets);return;}if(p&&request===importRequest.current){replaceProject({...p,recoveryId:p.template?crypto.randomUUID():p.recoveryId,assets:p.assets.map(prepareAsset)},true);setNotice(p.template?'Шаблон открыт. Выберите исходник и нажмите «Заменить».':'Проект открыт');}},true);}
 async function recover(){const request=importRequest.current;await task(async operationId=>{const entry=recoveries.find(e=>e.id===recoveryId);if(!entry)return;await ensureNativeSession();if(request!==importRequest.current)return;const p=await invoke<Project>('editor_restore',{project:{...entry.project,recoveryId:entry.id},owner:editorOwner.current,operationId});if(!mounted.current||request!==importRequest.current){discardPreviews(p.assets);return;}replaceProject({...p,recoveryId:entry.id,assets:p.assets.map(prepareAsset)},false);setRestorePrompt(false);},true);}
 function update(patch:Partial<Item>){if(selection)change({...project,items:project.items.map(i=>i.id===selection.id?{...i,...patch}:i)});}
 const drag=useRef<{x:number;base:Project;id:string;mode:'move'|'left'|'right'}|null>(null);
 function trimKey(e:React.KeyboardEvent,id:string,mode:'left'|'right'){
  if(isRendering||e.ctrlKey||e.metaKey||!['ArrowLeft','ArrowRight'].includes(e.key))return;
  e.preventDefault();e.stopPropagation();setSelected(id);setPlaying(false);
  const base=current.current,delta=(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?10:1)/base.fps;
  change(changeGroup(base,id,mode,delta));
 }
 function startDrag(e:React.PointerEvent,id:string,mode:'move'|'left'|'right'){if(isRendering||e.button!==0)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);setSelected(id);setPlaying(false);past.current=[...past.current.slice(-99),project];future.current=[];drag.current={x:e.clientX,base:project,id,mode};}
 function moveDrag(e:React.PointerEvent){const d=drag.current;if(d){const delta=(e.clientX-d.x)/zoom;const snapped=e.ctrlKey?{delta,at:undefined}:snapDelta(d.base,d.id,d.mode,delta,8/zoom);setSnapAt(snapped.at);setProject(changeGroup(d.base,d.id,d.mode,snapped.delta));}}
 function finishDrag(){drag.current=null;setSnapAt(undefined);refreshHistory(v=>v+1);}
 function beginLevel(id:string){setSelected(id);past.current=[...past.current.slice(-99),current.current];future.current=[];}
 function setLevel(id:string,value:number){setProject(p=>({...p,items:p.items.map(i=>i.id===id?{...i,[i.kind==='audio'?'gain':'opacity']:value}:i)}));}
 function commitLevel(id:string,value:number){change({...current.current,items:current.current.items.map(i=>i.id===id?{...i,[i.kind==='audio'?'gain':'opacity']:value}:i)});}
 useEffect(()=>{function key(e:KeyboardEvent){const time=clock.getSnapshot();if((e.target as HTMLElement).closest('input,textarea,select,[role=combobox],[role=listbox]')||exporting||openPrompt||closePrompt||context)return;if(e.code==='Space'){e.preventDefault();if(time>=total)setTime(0);if(!playing)setError('');setPlaying(v=>!v);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void save();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(selected&&e.key==='Delete')change(remove(current.current,selected,ripple));if(selected&&e.key.toLowerCase()==='s'&&!e.ctrlKey)change(split(current.current,selected,time));}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[clock,total,playing,selected,ripple,exporting,openPrompt,closePrompt,context,undo,redo]);
 const {plan,planError}=useMemo(()=>{try{return {plan:exportPlan(project,outWidth,outHeight,outFps,bitrate,discord,priority,discordLimitMb),planError:''};}catch(e){return {plan:undefined,planError:String(e)};}},[project,outWidth,outHeight,outFps,bitrate,discord,priority,discordLimitMb]);
 async function render(){if(!plan)return;setPlaying(false);await task(async()=>{const rasters=[];for(const i of project.items.filter(i=>i.kind==='text')){const canvas=document.createElement('canvas');canvas.width=Math.max(2,Math.round(plan!.width*i.width));canvas.height=Math.max(2,Math.round(plan!.height*i.height));const ctx=canvas.getContext('2d')!;ctx.fillStyle=i.color;ctx.font=`600 ${i.fontSize*plan!.width/project.width}px Arial`;ctx.textBaseline='top';i.text.split('\n').forEach((line,n)=>ctx.fillText(line,0,n*i.fontSize*plan!.width/project.width*1.2));const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Не удалось подготовить текст')),'image/png'));rasters.push({id:i.id,bytes:Array.from(new Uint8Array(await blob.arrayBuffer()))});}const accepted=await invoke<boolean>('editor_export',{project:clean(project),plan,rasters});if(accepted)setStatus({state:'running',progress:0});});}
 const rulerRef=useRef<HTMLDivElement>(null);const seeking=useRef(false);
 function seek(e:React.PointerEvent){const r=rulerRef.current?.getBoundingClientRect();if(r)setTime(Math.max(0,Math.min(total,(e.clientX-r.left)/zoom)));}
 function beginSeek(e:React.PointerEvent){if(e.button!==0)return;e.preventDefault();e.stopPropagation();setPlaying(false);seeking.current=true;e.currentTarget.setPointerCapture(e.pointerId);seek(e);}
 function moveSeek(e:React.PointerEvent){if(seeking.current)seek(e);}
 function endSeek(){seeking.current=false;}
 const pendingClose=useRef<(()=>void)|null>(null);
 function finishClose(){const action=pendingClose.current;pendingClose.current=null;setClosePrompt(false);if(autosaveActive.current)persistAutosave(current.current);action?.();}
 function cancelClose(){pendingClose.current=null;setClosePrompt(false);}
 function requestClose(action:()=>void=onClose){if(busy||isRendering){setNotice('Дождитесь завершения текущей операции или отмените рендер.');return;}setPlaying(false);if(dirty){if(!pendingClose.current)pendingClose.current=action;setClosePrompt(true);}else{if(autosaveActive.current)persistAutosave(current.current);action();}}
 const navigationHandler=useRef(requestClose);navigationHandler.current=requestClose;
 useLayoutEffect(()=>registerNavigationGuard(action=>navigationHandler.current(action)),[]);
 useEffect(()=>{function block(e:KeyboardEvent){if(e.key==='F12'||(e.ctrlKey&&e.shiftKey&&['i','j','c'].includes(e.key.toLowerCase()))){e.preventDefault();e.stopImmediatePropagation();}}window.addEventListener('keydown',block,true);return()=>window.removeEventListener('keydown',block,true);},[]);
 const contextItem=project.items.find(i=>i.id===context?.id);
 const menuActions:MenuAction[]=contextItem?[
 {label:'Перейти к началу',run:()=>{setPlaying(false);setTime(contextItem.start);}},
 {label:'Разрезать в позиции курсора',disabled:time<=contextItem.start+.02||time>=contextItem.start+contextItem.duration-.02,run:()=>change(split(current.current,contextItem.id,time))},
 {label:'Дублировать',run:()=>change(duplicate(current.current,contextItem.id))},
 ...(contextItem.kind==='audio'?[{label:contextItem.gain===0?'Включить звук':'Отключить звук',run:()=>update({gain:contextItem.gain===0?1:0})},{label:'Громкость 100%',run:()=>update({gain:1})}]:[{label:'Непрозрачность 100%',run:()=>update({opacity:1})}]),
 ...(contextItem.kind==='text'?[{label:'Редактировать текст',run:()=>setInspectorVisible(true)}]:contextItem.kind!=='audio'?[{label:'Вписать в кадр',run:()=>{const a=assetsById.get(contextItem.asset??'');if(a&&a.width&&a.height){const scale=Math.min(project.width/a.width,project.height/a.height),width=a.width*scale/project.width,height=a.height*scale/project.height;update({width,height,x:(1-width)/2,y:(1-height)/2,fit:'contain'});}}}]:[]),
 ...(contextItem.link?[{label:'Отделить дорожку',run:()=>update({link:undefined})}]:[]),
 {label:'Удалить',danger:true,run:()=>change(remove(current.current,contextItem.id,ripple))}
 ]:[];
 const timelineWidth=Math.max(900,(total+5)*zoom);const steps=Math.max(1,Math.round(100/zoom));
 return <div className="ed" role="dialog" aria-modal="true" aria-label="Редактор клипов" onContextMenu={e=>e.preventDefault()}>
 <header className="ed-header" data-tauri-drag-region><div><button aria-label="Назад" disabled={isRendering||busy} onClick={()=>requestClose()}><ArrowLeft size={16}/>Назад</button><span className="ed-brand"><Film size={17}/>Редактор клипов</span><input aria-label="Название проекта" value={project.name} onChange={e=>change({...project,name:e.target.value})}/></div><nav>
 <button disabled={busy||isRendering} onClick={()=>void openProject()}><FolderOpen size={16}/>Открыть</button><button disabled={busy||isRendering} onClick={()=>void save()}><Save size={16}/>Сохранить</button><button disabled={busy||isRendering} onClick={()=>void save(true)} title="Скопировать исходники вместе с проектом"><Package size={16}/></button><button className="ed-primary" disabled={!total||busy||isRendering} onClick={()=>{setOutWidth(project.width);setOutHeight(project.height);setOutFps(project.fps);setExporting(true);}}><Download size={16}/>Экспорт</button><button aria-label="Свернуть окно" onClick={()=>{if('__TAURI_INTERNALS__' in window)void getCurrentWindow().minimize().catch(e=>setError(String(e)));}}><Minus size={18}/></button><button aria-label={fullscreen?'Выйти из полноэкранного режима':'Полноэкранный режим'} title={fullscreen?'Выйти из полноэкранного режима':'Полноэкранный режим'} onClick={()=>{if('__TAURI_INTERNALS__' in window){void windowSession.current?.toggleFullscreen().then(setFullscreen).catch(e=>setError(String(e)));}}}>{fullscreen?<Minimize size={17}/>:<Maximize size={17}/>}</button><button aria-label="Закрыть редактор" disabled={isRendering||busy} onClick={()=>requestClose()}><X size={20}/></button></nav></header>
 {(error||notice||busy)&&<div className={`ed-message ${error?'ed-error':''}`} role={error?'alert':'status'}>{busy?(importProgress?formatImportProgress(importProgress):'Подготавливаем медиа…'):error||notice}{importing&&<button onClick={cancelImport}>Отменить импорт</button>}<button onClick={()=>{setError('');setNotice('');}} aria-label="Скрыть сообщение"><X size={14}/></button></div>}
 <div className={`ed-message ${autosaveError?'ed-error':''}`} role={autosaveError?'alert':'status'} aria-label="Состояние автокопии">{autosaveError||autosaveStatus}{autosaveError&&<button disabled={busy} onClick={()=>persistAutosave(current.current)}>Повторить автосохранение</button>}</div>
 {recoveryWarning&&<div className="ed-message ed-error" role="alert">{recoveryWarning}</div>}
 <div className={`ed-workspace ${inspectorVisible?'':'ed-inspector-hidden'}`}><aside className="ed-assets"><div className="ed-section-title">ИСХОДНИКИ<button disabled={busy||isRendering} onClick={()=>void importMedia()} aria-label="Добавить медиа"><Plus size={17}/></button></div><p className="ed-hint">Видео, изображения и звук. Исходники остаются нетронутыми.</p>
 {project.assets.map(a=><div className={`ed-asset ${a.missing?'ed-error':''}`} key={a.id}><button title={a.path} onClick={()=>{const i=project.items.find(i=>i.asset===a.id);if(i){setSelected(i.id);setTime(i.start);}}}>{a.kind==='audio'?<Volume2 size={18}/>:<Film size={18}/>}<span>{a.name}<small>{a.missing?'Файл не найден':`${seconds(a.duration)}${a.width?` · ${a.width}×${a.height}`:''}`}</small></span></button><div><button disabled={busy||isRendering} onClick={()=>change(addAsset(project,a,clock.getSnapshot()))}>На шкалу</button><button disabled={busy||isRendering} onClick={()=>void importMedia(undefined,a.id)}>Заменить</button></div></div>)}
 <button className="ed-wide" disabled={busy||isRendering} onClick={()=>void importMedia()}><Plus size={16}/>Добавить медиа</button><button className="ed-wide" disabled={isRendering} onClick={()=>{const time=clock.getSnapshot();const i={...newItem('text',Math.max(-1,...project.items.map(i=>i.track))+1,time,Math.max(1,Math.min(5,total-time||5))),x:.05,y:.05,width:.9,height:.4};change({...project,items:[...project.items,i]});setSelected(i.id);}}><Type size={16}/>Добавить текст</button><button className="ed-wide" disabled={!total||busy||isRendering} onClick={()=>void save(false,true)}>Сохранить как шаблон</button></aside>
 <main className="ed-preview"><div className="ed-screen-wrap" ref={previewWrap}><div className="ed-screen" style={{width:previewSize.width,height:previewSize.height,aspectRatio:`${project.width}/${project.height}`}}>{previewItems.map(i=><PlaybackActive clock={clock} start={i.start} duration={i.duration} key={i.id}>{active=><div className="ed-preview-layer"><Media item={i} asset={assetsById.get(i.asset??'')} clock={clock} active={active} playing={playing} canvasWidth={project.width} onPlaybackError={onPlaybackError}/>{i.kind!=='audio'&&active&&<PreviewTransform item={i} selected={selected===i.id} disabled={isRendering} onSelect={()=>{setSelected(i.id);setPlaying(false);}} onBegin={()=>beginLevel(i.id)} onChange={next=>{setProject(p=>({...p,items:p.items.map(v=>v.id===i.id?next:v)}));}} onEnd={()=>refreshHistory(v=>v+1)}/>}</div>}</PlaybackActive>)}{!total&&<div className="ed-preview-empty"><Film size={36}/><p>Ваш монтаж начинается здесь</p><button onClick={()=>void importMedia()}>Добавить первый клип</button></div>}</div></div>
 <PlaybackTime clock={clock}>{time=><div className="ed-transport"><button className="ed-play-button" aria-label={playing?'Пауза':'Воспроизвести'} disabled={!total} onClick={()=>{if(time>=total)setTime(0);if(!playing)setError('');setPlaying(v=>!v);}}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><span>{seconds(time)} <small>/ {seconds(total)}</small></span><input type="range" min="0" max={Math.max(total,.01)} step="0.01" value={Math.min(time,total)} onChange={e=>{setPlaying(false);setTime(+e.target.value);}} aria-label="Позиция воспроизведения"/><button className="ed-inspector-toggle" aria-pressed={inspectorVisible} onClick={()=>setInspectorVisible(v=>!v)}>Свойства</button></div>}</PlaybackTime></main>
 <aside className="ed-properties"><div className="ed-section-title">КОМПОЗИЦИЯ</div><label>Формат кадра<NativeSelect aria-label="Формат кадра" value={`${project.width}/${project.height}`} onChange={e=>{const [width,height]=e.target.value.split('/').map(Number);const scale=Math.min(width/project.width,height/project.height);change({...project,width,height,items:project.items.map(i=>i.kind==='audio'||i.kind==='text'?i:{...i,width:i.width*project.width*scale/width,height:i.height*project.height*scale/height,x:(1-(i.width*project.width*scale/width))/2+(i.x-(1-i.width)/2)*project.width*scale/width,y:(1-(i.height*project.height*scale/height))/2+(i.y-(1-i.height)/2)*project.height*scale/height})});}}><NativeSelectOption value={`${project.width}/${project.height}`}>{project.width} × {project.height}</NativeSelectOption><NativeSelectOption value="1920/1080">16:9 · Горизонтальный</NativeSelectOption><NativeSelectOption value="1080/1920">9:16 · TikTok / Shorts</NativeSelectOption><NativeSelectOption value="1080/1080">1:1 · Квадрат</NativeSelectOption><NativeSelectOption value="1080/1350">4:5 · Лента</NativeSelectOption></NativeSelect></label>
 <div className="ed-section-title">{selection?'ФРАГМЕНТ':'ВЫБЕРИТЕ ФРАГМЕНТ'}</div>{selection&&<><p className="ed-selected-name">{selection.kind==='text'?'Текст':selectedAsset?.name}</p><div className="ed-pair"><label>Начало, с<input type="number" min="0" step=".1" value={+selection.start.toFixed(2)} onChange={e=>change(changeGroup(project,selection.id,'move',+e.target.value-selection.start))}/></label><label>Длина, с<input type="number" min=".05" step=".1" value={+selection.duration.toFixed(2)} onChange={e=>change(changeGroup(project,selection.id,'right',+e.target.value-selection.duration))}/></label></div><label>Вход в исходник, с<input type="number" min="0" step=".1" value={+selection.source.toFixed(2)} onChange={e=>change(changeSource(project,selection.id,+e.target.value))}/></label>
 {selection.link&&<button className="ed-wide" onClick={()=>change({...project,items:project.items.map(i=>i.id===selection.id?{...i,link:undefined}:i)})}><Unlink size={15}/>Отделить дорожку</button>}
 {selection.kind==='audio'?<label>Громкость · {Math.round(selection.gain*100)}%<input type="range" min="0" max="1" step=".01" value={selection.gain} onChange={e=>update({gain:+e.target.value})}/></label>:<>
 {selection.kind==='text'&&<><label>Текст<textarea aria-label="Текст" rows={3} value={selection.text} onChange={e=>update({text:e.target.value})}/></label><div className="ed-pair"><label>Размер<input type="number" min="8" max="500" value={selection.fontSize} onChange={e=>update({fontSize:Math.max(8,+e.target.value)})}/></label><label>Цвет<input type="color" value={selection.color} onChange={e=>update({color:e.target.value})}/></label></div></>}
 <div className="ed-pair">{(['x','y','width','height'] as const).map(key=><label key={key}>{{x:'X, %',y:'Y, %',width:'Ширина, %',height:'Высота, %'}[key]}<input type="number" min={key==='width'||key==='height'?1:-100} max="200" value={Math.round(selection[key]*100)} onChange={e=>update({[key]:Math.max(key==='width'||key==='height'?.01:-1,Math.min(2,+e.target.value/100))})}/></label>)}</div>
 {selection.kind!=='text'&&selectedAsset&&<div className="ed-pair">{(['contain','cover'] as const).map(fit=><button key={fit} onClick={()=>{const factor=(fit==='contain'?Math.min:Math.max)(project.width/selectedAsset.width,project.height/selectedAsset.height);const width=selectedAsset.width*factor/project.width,height=selectedAsset.height*factor/project.height;update({width,height,x:(1-width)/2,y:(1-height)/2,fit:'contain'});}}>{fit==='contain'?'Вписать в кадр':'Заполнить кадр'}</button>)}</div>}
 {selection.kind!=='text'&&<label>Заполнение<NativeSelect aria-label="Заполнение" value={selection.fit} onChange={e=>update({fit:e.target.value as Item['fit']})}><NativeSelectOption value="contain">Вписать целиком</NativeSelectOption><NativeSelectOption value="cover">Заполнить кадр</NativeSelectOption></NativeSelect></label>}
 <label>Непрозрачность<input type="range" min="0" max="1" step=".01" value={selection.opacity} onChange={e=>update({opacity:+e.target.value})}/></label>
 {selection.kind==='video'&&(['brightness','contrast','saturation'] as const).map(key=><label key={key}>{{brightness:'Яркость',contrast:'Контраст',saturation:'Насыщенность'}[key]}<input type="range" min={key==='brightness'?-.8:0} max={key==='brightness'?.8:2} step=".01" value={selection[key]} onChange={e=>update({[key]:+e.target.value})}/></label>)}
 </>}</>}
 <p className="ed-hint">S — разрезать · Delete — удалить · Ctrl+Z — отменить · Ctrl+S — сохранить</p></aside></div>
 <section className="ed-timeline"><div className="ed-timeline-tools"><button disabled={!past.current.length||isRendering} title="Отменить" onClick={undo}><Undo2 size={17}/></button><button disabled={!future.current.length||isRendering} title="Повторить" onClick={redo}><Redo2 size={17}/></button><span data-history={historyRevision}/><span className="ed-timeline-caption">Монтаж</span><button disabled={!selection||isRendering} onClick={()=>selected&&change(split(project,selected,clock.getSnapshot()))}><Scissors size={16}/>Разрезать</button><button disabled={!selection||isRendering} onClick={()=>selected&&change(remove(project,selected,ripple))}><Trash2 size={16}/>Удалить</button><label className="ed-check"><input type="checkbox" checked={ripple} onChange={e=>setRipple(e.target.checked)}/>Сдвигать после удаления</label><label className="ed-zoom">Масштаб<input type="range" min="8" max="100" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label></div>
 <div className="ed-timeline-scroll"><div className="ed-timeline-content" style={{width:timelineWidth+120}}><div className="ed-ruler" ref={rulerRef} style={{width:timelineWidth,marginLeft:120}} onPointerDown={beginSeek} onPointerMove={moveSeek} onPointerUp={endSeek} onPointerCancel={endSeek}>{Array.from({length:Math.ceil((total+5)/steps)},(_,n)=><span key={n} style={{left:n*steps*zoom}}>{seconds(n*steps).slice(0,-3)}</span>)}</div>
 {tracks.map(track=><div className="ed-track" key={track}><div className="ed-track-name" draggable={!isRendering} title="Перетащите, чтобы изменить порядок дорожек" onDragStart={e=>{e.dataTransfer.setData('application/x-rebcap-track',String(track));e.dataTransfer.effectAllowed='move';}} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-rebcap-track'))e.preventDefault();}} onDrop={e=>{e.preventDefault();const raw=e.dataTransfer.getData('application/x-rebcap-track');if(raw&&!isRendering)change(reorderTrack(project,Number(raw),track));}}>{trackItems.get(track)?.[0]?.kind==='audio'?<Volume2 size={14}/>:<Film size={14}/>}<span>Дорожка {track+1}</span><div className="ed-track-order"><button aria-label={`Поднять дорожку ${track+1}`} disabled={isRendering||tracks.indexOf(track)===0} onClick={()=>change(reorderTrack(project,track,tracks[tracks.indexOf(track)-1]))}><ArrowUp size={12}/></button><button aria-label={`Опустить дорожку ${track+1}`} disabled={isRendering||tracks.indexOf(track)===tracks.length-1} onClick={()=>change(reorderTrack(project,track,tracks[tracks.indexOf(track)+1]))}><ArrowDown size={12}/></button></div></div><div className="ed-track-lane" style={{width:timelineWidth}} onPointerDown={e=>{if(e.target===e.currentTarget){setSelected(undefined);setPlaying(false);setTime(Math.max(0,Math.min(total,(e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom)));}}}>
 {(trackItems.get(track)??[]).map(i=><div key={i.id} className={`ed-item ed-${i.kind} ${selected===i.id?'ed-item-selected':''} ${i.gain===0&&i.kind==='audio'?'ed-muted':''}`} style={{left:i.start*zoom,width:Math.max(8,i.duration*zoom)}} onContextMenu={e=>{e.preventDefault();e.stopPropagation();if(isRendering)return;setSelected(i.id);setPlaying(false);setContext({x:e.clientX,y:e.clientY,id:i.id});}} onPointerDown={e=>startDrag(e,i.id,'move')} onPointerMove={moveDrag} onPointerUp={finishDrag} onPointerCancel={finishDrag} onDoubleClick={()=>{setTime(i.start);setSelected(i.id);}} title={`${i.kind==='text'?i.text:assetsById.get(i.asset??'')?.name} · ${seconds(i.source)} → ${seconds(i.source+i.duration)}`}><button className="ed-handle ed-left" aria-label="Подрезать начало" disabled={isRendering} title="Стрелки: 1 кадр; Shift: 10 кадров" onKeyDown={e=>trimKey(e,i.id,'left')} onPointerDown={e=>startDrag(e,i.id,'left')} onPointerMove={moveDrag} onPointerUp={finishDrag} onPointerCancel={finishDrag}/><span className="ed-item-name">{i.kind==='text'?i.text:i.kind==='audio'?(assetsById.get(i.asset??'')?.audioUrls?.[assetsById.get(i.asset??'')?.audio.indexOf(i.stream)??0]?.label??'Аудио'):assetsById.get(i.asset??'')?.name}</span>{(i.kind==='audio'||i.kind==='video')&&<span className="ed-level-fill" aria-hidden="true" style={{top:`calc(${(1-(i.kind==='audio'?i.gain:i.opacity))*100}% + ${(2*(i.kind==='audio'?i.gain:i.opacity)-1)*12}px)`}}/>}{(i.kind==='audio'||i.kind==='video')&&<span className="ed-level-scale" aria-hidden="true"/>}{(i.kind==='audio'||i.kind==='video')&&<TimelineLevel value={i.kind==='audio'?i.gain:i.opacity} label={`${i.kind==='audio'?'Громкость':'Прозрачность'} ${assetsById.get(i.asset??'')?.name??'фрагмента'}`} disabled={isRendering} onSelect={()=>setSelected(i.id)} onBegin={()=>beginLevel(i.id)} onChange={value=>setLevel(i.id,value)} onEnd={()=>refreshHistory(v=>v+1)} onCommit={value=>commitLevel(i.id,value)}/>}<button className="ed-handle ed-right" aria-label="Подрезать конец" disabled={isRendering} title="Стрелки: 1 кадр; Shift: 10 кадров" onKeyDown={e=>trimKey(e,i.id,'right')} onPointerDown={e=>startDrag(e,i.id,'right')} onPointerMove={moveDrag} onPointerUp={finishDrag} onPointerCancel={finishDrag}/></div>)}
 </div></div>)}{!tracks.length&&<div className="ed-timeline-empty">Добавьте медиа, чтобы начать монтаж</div>}<>{snapAt!==undefined&&<div className="ed-snap-guide" style={{left:120+snapAt*zoom}}/>}</><PlaybackTime clock={clock}>{time=><><div className="ed-playhead-line" style={{left:120+time*zoom}}/><div className="ed-playhead" role="slider" tabIndex={0} aria-label="Курсор таймлайна" aria-valuemin={0} aria-valuemax={total} aria-valuenow={time} style={{left:114+time*zoom}} onPointerDown={beginSeek} onPointerMove={moveSeek} onPointerUp={endSeek} onPointerCancel={endSeek} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setPlaying(false);setTime(t=>Math.max(0,Math.min(total,t+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?1:1/project.fps))));}}}/></>}</PlaybackTime></div></div></section>
 {context&&contextItem&&<TimelineMenu x={context.x} y={context.y} actions={menuActions} onClose={()=>setContext(undefined)}/>}
 {exporting&&<div className="ed-modal-backdrop"><section className="ed-modal ed-export-modal" role="dialog" aria-label="Экспорт видео"><header><h2>Готовое видео</h2><button disabled={isRendering} onClick={()=>setExporting(false)} aria-label="Закрыть экспорт"><X size={20}/></button></header><div className="ed-export-body"><p className="ed-hint">MP4 · H.264 · AAC. Исходники сохраняются.</p><div className="ed-pair"><label>Ширина<input type="number" min="16" max="7680" step="2" disabled={isRendering} value={outWidth} onChange={e=>setOutWidth(+e.target.value)}/></label><label>Высота<input type="number" min="16" max="7680" step="2" disabled={isRendering} value={outHeight} onChange={e=>setOutHeight(+e.target.value)}/></label><label>FPS<NativeSelect aria-label="FPS" disabled={isRendering} value={outFps} onChange={e=>setOutFps(+e.target.value)}>{[24,30,60,120].map(f=><NativeSelectOption key={f} value={f}>{f}</NativeSelectOption>)}</NativeSelect></label><label>Битрейт, Мбит/с<input type="number" min=".1" max="200" step=".5" disabled={isRendering||discord} value={bitrate} onChange={e=>setBitrate(+e.target.value)}/></label></div><label className="ed-discord" data-enabled={discord} style={{backgroundImage:`linear-gradient(90deg,rgba(8,10,32,.97) 0%,rgba(8,10,32,.88) 42%,rgba(8,10,32,.35) 70%,rgba(8,10,32,.12) 100%),radial-gradient(ellipse at 85% 40%,#5865f2 0%,#2a2668 38%,#080a20 78%)`}}><input className="ed-discord-input" type="checkbox" aria-label="Подготовить для отправки в Discord" checked={discord} disabled={isRendering} onChange={e=>setDiscord(e.target.checked)}/><span className="ed-discord-copy"><span className="ed-discord-topline"><span className="ed-discord-switch" aria-hidden="true"/><span>DISCORD</span></span><strong>Подготовить<br/>для друзей</strong><small>До {discordLimitMb} МБ · оптимизация видео<br/>Размер проверим после рендера</small></span></label>{discord&&<><label>Лимит загрузки Discord<NativeSelect aria-label="Лимит загрузки Discord" disabled={isRendering} value={discordLimitMb} onChange={e=>setDiscordLimitMb(+e.target.value)}><NativeSelectOption value="20">Без подписки · 20 МБ</NativeSelectOption><NativeSelectOption value="50">Nitro Basic · 50 МБ</NativeSelectOption><NativeSelectOption value="500">Nitro · 500 МБ</NativeSelectOption></NativeSelect></label><label>Приоритет качества<NativeSelect aria-label="Приоритет качества" disabled={isRendering} value={priority} onChange={e=>setPriority(e.target.value)}><NativeSelectOption value="auto">Автоматически</NativeSelectOption><NativeSelectOption value="motion">Плавность движения — сохранить FPS</NativeSelectOption><NativeSelectOption value="detail">Детали — можно снизить FPS</NativeSelectOption></NativeSelect></label></>}
 <div className="ed-export-summary">{plan?`${plan.width} × ${plan.height} · ${plan.fps} FPS · ${(plan.bitrate/1e6).toFixed(2)} Мбит/с · ~${((plan.bitrate+128000)*total/8/1e6).toFixed(1)} МБ`:planError}</div>{isRendering&&<><div className="ed-render-progress" role="progressbar" aria-label="Прогресс рендера" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round((status.progress??0)*100)}><span style={{width:`${Math.max(0,Math.min(1,status.progress??0))*100}%`}}/></div><p>Рендер · {Math.round((status.progress??0)*100)}% {status.attempt&&status.attempt>1?`· проход ${status.attempt}`:''}</p></>}{status.state==='done'&&<p className="ed-success">Сохранено · {((status.bytes??0)/1e6).toFixed(2)} МБ</p>}{status.state==='error'&&<p className="ed-error">{status.error}</p>}<button className="ed-primary ed-wide" disabled={busy||!plan||!total} onClick={()=>isRendering?void invoke('editor_cancel'):void render()}>{isRendering?'Отменить рендер':'Рендерить и сохранить'}</button></div></section></div>}
 <ConfirmDialog open={openPrompt} title="Открыть другой проект?" description="Для надёжного хранения текущего монтажа сначала сохраните его в .rebcap." confirmLabel="Открыть проект" onCancel={()=>setOpenPrompt(false)} onConfirm={()=>{setOpenPrompt(false);void openProject(true);}}/>
 {closePrompt&&<div className="ed-modal-backdrop"><section className="ed-modal"><h2>Сохранить монтаж?</h2><p>В проекте есть несохранённые изменения. Сохраните .rebcap, чтобы выбрать место хранения проекта. Локальная автокопия не заменяет файл проекта.</p>{autosaveError&&<p className="ed-error" role="alert">{autosaveError}</p>}<button className="ed-wide ed-primary" disabled={busy} onClick={()=>{void save().then(saved=>{if(saved)finishClose();});}}>Сохранить .rebcap</button><button className="ed-wide" disabled={busy} onClick={finishClose}>Закрыть без сохранения</button><button className="ed-wide" disabled={busy} onClick={cancelClose}>Продолжить монтаж</button></section></div>}
 {restorePrompt&&<div className="ed-modal-backdrop"><section className="ed-modal"><h2>Продолжить предыдущий монтаж?</h2><p>Выберите локальную автокопию. Другие проекты останутся в хранилище.</p><label>Автокопия для восстановления<NativeSelect aria-label="Автокопия для восстановления" disabled={busy} value={recoveryId} onChange={e=>setRecoveryId(e.target.value)}>{recoveries.map(entry=><NativeSelectOption key={entry.id} value={entry.id}>{entry.project.name} · {entry.savedAt?new Date(entry.savedAt).toLocaleString():'Предыдущая версия'}</NativeSelectOption>)}</NativeSelect></label><button className="ed-primary ed-wide" disabled={busy} onClick={()=>void recover()}>Восстановить</button><button className="ed-wide" onClick={()=>setRestorePrompt(false)}>Новый проект</button></section></div>}
 </div>;
}
