import { describe,it,expect } from 'vitest';
import {duplicate,snapDelta,reorderTrack,addAsset,emptyProject,split,remove,changeGroup,changeSource,exportPlan,length} from './model';
const fixture=()=>addAsset(emptyProject(),{id:'a',path:'a.mp4',name:'a',kind:'video',duration:30,width:1920,height:1080,audio:[1,2]});
describe('non-destructive editor',()=>{
 it('budgets every Discord tier and rejects unsupported limits',()=>{const p=fixture();p.items=p.items.map(i=>({...i,duration:120}));const rates=[20,50,500].map(limit=>{const plan=exportPlan(p,1920,1080,60,12,true,'auto',limit);expect((plan.bitrate+128000)*120/8+65536).toBeLessThan(limit*1e6);expect(plan.discordLimitMb).toBe(limit);return plan.bitrate;});expect(rates[1]).toBeGreaterThan(rates[0]);expect(rates[2]).toBeGreaterThan(rates[1]);expect(()=>exportPlan(p,1920,1080,60,12,true,'auto',30)).toThrow();});
 it('duplicates linked media into a new independent group with matching offsets',()=>{const p=fixture(),q=duplicate(p,p.items[0].id);expect(q.items).toHaveLength(6);expect(q.items.slice(3).every(i=>i.start===30&&i.link===q.items[3].link&&i.link!==p.items[0].link)).toBe(true);expect(new Set(q.items.map(i=>i.id)).size).toBe(6);});
 it('snaps either clip edge only to neighbors on the same track',()=>{let p=fixture();p=split(p,p.items[0].id,10);const id=p.items[0].id;expect(snapDelta(p,id,'move',.1,.2).delta).toBeCloseTo(0);expect(snapDelta(p,id,'move',.1,.2).at).toBe(10);expect(snapDelta(p,id,'right',-.1,.2).delta).toBeCloseTo(0);expect(snapDelta(p,id,'move',2,.2)).toEqual({delta:2,at:undefined});expect(snapDelta(p,p.items.find(i=>i.kind==='audio')!.id,'move',.1,.2)).toEqual({delta:.1});});
 it('reorders whole tracks while preserving links, timing and level',()=>{const p=fixture(),before=p.items[0],next=reorderTrack(p,0,2);expect(next.items[0]).toEqual({...before,track:2});expect(next.items[1].track).toBe(0);expect(next.items[2].track).toBe(1);expect(p.items[0].track).toBe(0);});
 it('splits linked video and independent audio at the same source offset',()=>{const p=fixture(),q=split(p,p.items[0].id,10);expect(q.items).toHaveLength(6);expect(q.items.filter(i=>i.start===10).map(i=>i.source)).toEqual([10,10,10]);expect(p.items).toHaveLength(3);});
 it('removes middle and ripples later media without moving source offsets',()=>{let p=fixture();p=split(p,p.items[0].id,10);const middle=p.items.find(i=>i.start===10)!;p=split(p,middle.id,20);p=remove(p,middle.id,true);expect(length(p)).toBe(20);expect(p.items.filter(i=>i.start===10).every(i=>i.source===20)).toBe(true);});
 it('clamps trim to media bounds and updates linked audio',()=>{const p=fixture();const q=changeGroup(p,p.items[0].id,'left',5);expect(q.items.every(i=>i.source===5&&i.duration===25)).toBe(true);expect(length(changeGroup(q,q.items[0].id,'right',100))).toBe(30);});
 it('budgets container and audio below Discord ceiling',()=>{const p=fixture();const plan=exportPlan(p,1920,1080,60,20,true,'auto');expect((plan.bitrate+128000)*30/8+65536).toBeLessThanOrEqual(19_000_000);expect(plan.width%2).toBe(0);});
 it('prioritizes motion or detail differently for a long clip',()=>{const p=fixture();p.items=p.items.map(i=>({...i,duration:90}));const motion=exportPlan(p,1920,1080,60,20,true,'motion'),detail=exportPlan(p,1920,1080,60,20,true,'detail');expect(motion.fps).toBe(60);expect(detail.width).toBeGreaterThanOrEqual(motion.width);expect(detail.fps).toBeLessThan(motion.fps);});
 it('rejects impossible limits and invalid output parameters',()=>{const p=fixture();p.items=p.items.map(i=>({...i,duration:10000}));expect(()=>exportPlan(p,1920,1080,60,20,true,'auto')).toThrow();expect(()=>exportPlan(fixture(),0,1080,60,20,false,'auto')).toThrow();});
 it('keeps linked source offsets in sync and reuses imported media',()=>{let p=fixture();p=changeGroup(p,p.items[0].id,'right',-10);p=changeSource(p,p.items[0].id,5);expect(p.items.every(i=>i.source===5)).toBe(true);expect(addAsset(p,p.assets[0]).assets).toHaveLength(1);});
});
