import {NativeSelect,NativeSelectOption} from '../components/ui/native-select';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {GripVertical,Plus,Save,Trash2} from 'lucide-react';
import {blocks,defaults,previewName,readParts,type Part,type NamingSettings as Settings} from './model';
import './naming.css';
import {dropMarker} from './dropMarker';

function Builder({parts,resetKey,onChange,disabled}:{parts:Part[];resetKey:number;disabled:boolean;onChange:(parts:Part[])=>void}){
 const [dropPoint,setDropPoint]=useState<{left:number;top:number;height:number}>();const dropRange=useRef<Range|null>(null);
 const root=useRef<HTMLDivElement>(null),selection=useRef<Range|null>(null),dragged=useRef<HTMLElement|null>(null);
 function block(value:string){const span=document.createElement('span');span.dataset.token=value;span.contentEditable='false';span.draggable=true;span.className='name-block name-block-arrive';span.textContent=blocks.find(b=>b.id===value)?.label??value;span.setAttribute('aria-label',span.textContent);return span;}
 useLayoutEffect(()=>{const el=root.current!;el.replaceChildren(...parts.map(p=>p.kind==='text'?document.createTextNode(p.value):block(p.value)));selection.current=null;},[resetKey]);
 function remember(){const s=window.getSelection();if(s?.rangeCount&&root.current?.contains(s.anchorNode))selection.current=s.getRangeAt(0).cloneRange();}
 function insert(node:Node,range=selection.current){const el=root.current!;if(!range||!el.contains(range.commonAncestorContainer)){range=document.createRange();range.selectNodeContents(el);range.collapse(false);}range.deleteContents();range.insertNode(node);range.setStartAfter(node);range.collapse(true);const s=window.getSelection();s?.removeAllRanges();s?.addRange(range);selection.current=range.cloneRange();el.focus();onChange(readParts(el));}
 function rangeAt(x:number,y:number){const range=(document as Document&{caretRangeFromPoint?:(x:number,y:number)=>Range|null}).caretRangeFromPoint?.(x,y)??null;if(!range||!root.current?.contains(range.commonAncestorContainer))return null;const hit=range.startContainer instanceof HTMLElement?range.startContainer:range.startContainer.parentElement;const target=hit?.closest<HTMLElement>('[data-token]');if(target){const rect=target.getBoundingClientRect();if(x<rect.x+rect.width/2)range.setStartBefore(target);else range.setStartAfter(target);range.collapse(true);}return range;}
 function finishDrag(){dragged.current?.classList.remove('name-block-dragging');dragged.current=null;dropRange.current=null;setDropPoint(undefined);}
 return <><div className="name-builder-wrap"><div className="name-builder" ref={root} role="textbox" aria-label="Конструктор имени записи" aria-multiline={false} contentEditable={!disabled} suppressContentEditableWarning spellCheck={false} onInput={()=>{remember();onChange(readParts(root.current!));}} onKeyUp={remember} onPointerUp={remember} onKeyDown={e=>{if(e.key==='Enter')e.preventDefault();}} onPaste={e=>{e.preventDefault();insert(document.createTextNode(e.clipboardData.getData('text/plain').replace(/[\r\n]+/g,' ')));}}
 onDragStart={e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-token]');if(!target)return;dragged.current=target;target.classList.add('name-block-dragging');e.dataTransfer.setData('application/x-rebcap-name-token',target.dataset.token!);e.dataTransfer.effectAllowed='move';}}
 onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-rebcap-name-token')){e.preventDefault();e.dataTransfer.dropEffect=dragged.current?'move':'copy';const range=rangeAt(e.clientX,e.clientY);dropRange.current=range;setDropPoint(range?dropMarker(range,root.current!):undefined);}}}
 onDrop={e=>{e.preventDefault();const value=e.dataTransfer.getData('application/x-rebcap-name-token');if(!blocks.some(b=>b.id===value))return;const range=dropRange.current??rangeAt(e.clientX,e.clientY);if(dragged.current&&root.current?.contains(dragged.current))dragged.current.remove();finishDrag();insert(block(value),range);}}
 onDragEnd={finishDrag} onDragLeave={e=>{if(!root.current?.contains(e.relatedTarget as Node))setDropPoint(undefined);}}/>{dropPoint&&<span className="name-drop-marker" aria-hidden="true" style={{left:dropPoint.left,top:dropPoint.top,height:dropPoint.height}}/>}</div>
 <p className="name-hint">Пишите свой текст между блоками. Перетаскивайте блоки в нужное место или добавляйте нажатием.</p>
 <div className="name-palette" aria-label="Готовые блоки">{blocks.map(b=><button type="button" key={b.id} draggable onDragStart={e=>{dragged.current=null;e.dataTransfer.setData('application/x-rebcap-name-token',b.id);e.dataTransfer.effectAllowed='copy';}} onClick={()=>insert(block(b.id))} title={b.sample}><GripVertical size={12}/>{b.label}<Plus size={12}/></button>)}</div></>;
}
export function RecordingNameSettings(){
 const [settings,setSettings]=useState(defaults),[parts,setParts]=useState<Part[]>(()=>defaults().presets[0].parts),[reset,setReset]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[newName,setNewName]=useState('');const [pendingPreset,setPendingPreset]=useState<string>();
 const native='__TAURI_INTERNALS__' in window;
 useEffect(()=>{let disposed=false;const load=(s:Settings)=>{if(disposed||!s?.presets?.length)return;const p=s.presets.find(p=>p.id===s.activeId);if(!p)return;setSettings(s);setParts(p.parts);setReset(v=>v+1);};if(native)void invoke<Settings>('get_recording_names').then(load).catch(e=>{if(!disposed)setError(String(e));});else{try{const saved=localStorage.getItem('rebcap.recordingNames');if(saved)load(JSON.parse(saved));}catch{/* Use default presets. */}}return()=>{disposed=true;};},[native]);
 async function save(next:Settings){setBusy(true);setError('');try{if(native)await invoke('set_recording_names',{settings:next});else localStorage.setItem('rebcap.recordingNames',JSON.stringify(next));setSettings(next);setParts(next.presets.find(p=>p.id===next.activeId)!.parts);setReset(v=>v+1);setDirty(false);setNotice('Пресет применяется к новым клипам и записям.');}catch(e){setError(String(e));}finally{setBusy(false);}}
 function apply(copy=false){if(!parts.length||!parts.some(p=>p.kind==='token'||p.value.trim())){setError('Добавьте текст или готовый блок.');return;}const current=settings.presets.find(p=>p.id===settings.activeId)!;const create=copy||['shadowplay','rebcap'].includes(current.id);const p={id:create?crypto.randomUUID():current.id,name:copy?newName.trim():create?'Мой пресет':current.name,parts};if(!p.name){setError('Укажите название пресета.');return;}void save({activeId:p.id,presets:create?[...settings.presets,p]:settings.presets.map(v=>v.id===p.id?p:v)}).then(()=>setNewName(''));}
 return <section className="recording-names" aria-label="Имена записей"><header><h3>Имена записей</h3><p>Соберите своё имя файла из текста и меток клипа.</p></header>
 <label className="name-label">Пресет<NativeSelect aria-label="Пресет имени записи" disabled={busy} value={settings.activeId} onChange={e=>{const id=e.target.value;if(dirty){setPendingPreset(id);return;}void save({...settings,activeId:id});}}>{settings.presets.map(p=><NativeSelectOption value={p.id} key={p.id}>{p.name}</NativeSelectOption>)}</NativeSelect></label>
 <fieldset disabled={busy} className="name-fieldset"><Builder disabled={busy} parts={parts} resetKey={reset} onChange={p=>{setParts(p);setDirty(true);setNotice('');}}/>
 <div className="name-preview"><span>ПРИМЕР ИМЕНИ</span><output aria-label="Пример имени записи">{previewName(parts)}</output></div>
 <p className="name-hint">Данные меток фиксируются при сохранении момента или начале записи. Время — локальное, расширенное время включает сотые секунды. Расширение добавляется автоматически.</p>
 <div className="name-actions"><button className="name-primary" disabled={!dirty} onClick={()=>apply()}><Save size={14}/>Применить имя</button>{!['shadowplay','rebcap'].includes(settings.activeId)&&<button onClick={()=>{const remaining=settings.presets.filter(p=>p.id!==settings.activeId);void save({activeId:remaining[0].id,presets:remaining});}} aria-label="Удалить пресет"><Trash2 size={14}/></button>}</div>
 <div className="name-save-row"><input aria-label="Название нового пресета" placeholder="Название нового пресета" maxLength={64} value={newName} onChange={e=>setNewName(e.target.value)}/><button disabled={!newName.trim()||settings.presets.length>=32} onClick={()=>apply(true)}><Plus size={14}/>Сохранить пресет</button></div></fieldset>
 {(error||notice)&&<p role={error?'alert':'status'} className={error?'name-error':'name-hint'}>{error||notice}</p>}
 <Dialog open={!!pendingPreset} onOpenChange={open=>{if(!open)setPendingPreset(undefined);}}><DialogContent className="name-confirm"><DialogTitle>Переключить пресет?</DialogTitle><DialogDescription>Изменения текущего имени ещё не сохранены. Можно продолжить редактирование или перейти к другому пресету.</DialogDescription><div className="name-confirm-actions"><button onClick={()=>setPendingPreset(undefined)}>Продолжить редактирование</button><button onClick={()=>{const id=pendingPreset!;setPendingPreset(undefined);void save({...settings,activeId:id});}}>Переключить без сохранения</button></div></DialogContent></Dialog>
 </section>;
}
