[package]
name = "rebelliocap-desktop"
version = "0.1.9"
edition = "2021"
rust-version = "1.90"

[lib]
name = "rebelliocap_desktop"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "RebellioCap"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", "protocol-asset"] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
tempfile = "3"
zip = { version = "2", default-features = false, features = ["deflate"] }
tauri-plugin-updater = "2"
base64 = "0.22.1"

[target.'cfg(windows)'.dependencies]
windows-version = "0.1"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Threading", "Win32_System_Diagnostics_ToolHelp", "Win32_System_SystemInformation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
windows = { version = "0.61", features = ["Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant", "Win32_Media_Audio", "Win32_Media_Audio_Endpoints", "Win32_UI_Shell", "Win32_UI_Shell_Common", "Win32_Foundation", "Win32_Graphics_Gdi"] }

[dev-dependencies]
minisign-verify = "0.2.5"
tempfile = "3"
